[workspace]

members = [
    "keriox_core",
    "keriox_tests",
    "support/gossip",
    "support/transport",
    "components/witness",
    "components/watcher",
    "components/controller",
    "tests",
]
