[package]
name = "keri-sdk"
version = "0.2.0"
description = "KERI Software Development Kit"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
keri-controller = { path = "../components/controller", version = "0.17.13" }
keri-core = { path = "../keriox_core", version = "0.17.13", features = ["query", "oobi"] }
cesrox = { version = "2.0.0-beta.7", features = ["cesr-proof"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_cbor = { version = "0.11" }
said = { version = "0.5.3-beta.1", features = ["macros"]}
teliox = { path = "../support/teliox", version = "0.17.13" }
thiserror = "1.0"
log = "0.4"
rand = "0.8.5"
ed25519-dalek = { version = "2.1.0", features = ["rand_core"] }
p256 = { version = "0.9", features = ["ecdsa", "sha256"] }
k256 = { version = "0.9", features = ["ecdsa", "sha256"] }
base64 = "0.13"
indexmap = { version = "2", features = ["serde"] }
tempfile = "3.10"
reqwest = { version = "0.12.22", default-features = false, features = ["rustls-tls", "json"] }
url = { version = "2.2.2", features = ["serde"] }

keri-keyprovider = { path = "../keri_keyprovider", version = "0.1.0", optional = true, features = ["software"] }
tokio = { version = "1", features = ["time"] }

[features]
default = []
keyprovider = ["keri-keyprovider", "tokio/full"]
mobile = ["keyprovider", "keri-keyprovider/host", "keri-keyprovider/software"]

[dev-dependencies]
tokio-test = "0.4"
keri-core = { path = "../keriox_core", version = "0.17.13" }
tokio = { version = "1", features = ["full"] }
witness = { path = "../components/witness" }
watcher = { path = "../components/watcher" }
test-context = "0.4.1"
actix-rt = "2.10.0"

[package.metadata.release]
publish = false
