[package]
name = "teliox"
version = "0.1.0"
authors = [
	"Edyta Pawlak <edyta.pawlak@opensoftware.pl>"
]
edition = "2021"
license = "EUPL-1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keri = {path = "../../keriox_core", features = ["oobi"]}
said = { git = "https://github.com/THCLab/cesrox", tag = "v0.1.4" }
cesrox = { git = "https://github.com/THCLab/cesrox", tag = "v0.1.4" }
version = { git = "https://github.com/THCLab/cesrox", tag = "v0.1.4" }
base64 = "0.13.0"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
serde-hex = "0.1"
chrono = { version = "0.4.18", features = ["serde"] }
arrayref = "0.3.6"
sled = { version = "0.34.6"}
serde_cbor = "0.11.1"
sled-tables = "0.2.0"
reqwest = { version = "0.11"}
async-trait = "0.1.57"


[dev-dependencies]
tempfile = "3.1"
