[package]
name = "keri-transport"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.57"
keri = { path = "../../keriox_core", features = ["controller", "oobi", "query"] }
reqwest = "0.11.11"
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0.32"
url = "2.2.2"
