[package]
name = "keri-controller"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
futures = "0.3.24"
keri-core = { path = "../../keriox_core", features = ["oobi", "mailbox"] }
teliox = {path = "../../support/teliox"}
thiserror = "1.0"
serde_json = "1.0"
url = "2.3.1"
cesrox = { version = "0.1.4" }
itertools = "0.11.0"

[dev-dependencies]
witness = { path = "../witness" }
tempfile = { version = "3.1" }