[package]
name = "controller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
keri = { path = "../../keriox_core", features = ["oobi", "controller"] }
keri-transport = { path = "../../support/transport" }
reqwest = { version = "0.11", features = ["json", "rustls-tls", "blocking"], default-features = false }
thiserror = "1.0"
serde_json = "1.0"

tempfile = { version = "3.1" }