[package]
name = "keri"
version = "0.8.0"
authors = [
    "Decentralized Identity Foundation",
    "Charles Cunningham <charles@jolocom.io>",
    "Ivan Temchenko <ivan@jolocom.io>",
    "Edyta Pawlak <edyta.pawlak@opensoftware.pl>",
]
edition = "2018"
description = "Core library for the Key Event Receipt Infrastructure "
license = "EUPL-1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
sled-db = ["sled", "fixed"]
async = ["async-std", "pin-project", "futures-core", "bitpat"]
default = ["sled-db"]
query = []
oobi = ["query", "url", "strum_macros", "strum"]
controller = ["oobi", "reqwest"]

[dependencies]
bytes = "1.3.0"
http = "0.2.8"
ed25519-dalek = "1.0.1"
k256 = { version = "0.9", features = ["ecdsa", "sha256", "zeroize"] }
blake2 = "0.9.1"
sha2 = "0.9.3"
sha3 = "0.9.1"
rand = { version = "0.7.3", features = ["std", "getrandom"] }
uuid = { version = "0.8", features = ["v4", "serde"] }
log = "0.4.16"
base64 = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.11.1"
serde_derive = "1.0.106"
thiserror = "1.0"
serde-hex = "0.1"
nom = "5"
itoa = "0.4"
ryu = "1.0"
blake3 = { version = "1", default-features = false }
chrono = { version = "0.4.18", features = ["serde"] }
rmp-serde = "0.15"
arrayref = "0.3.6"
zeroize = "1.3.0"
sled = { version = "0.34.6", optional = true }
fixed = { version = "1.9", optional = true }
fraction = { version = "0.9", features = ["with-serde-support"] }
# Async dependencies
async-trait = "0.1.57"
async-std = { version = "1", optional = true }
pin-project = { version = "1", optional = true }
futures-core = { version = "0.3.15", optional = true }
futures = { version = "0.3.13", optional = true }
bitpat = { version = "0.1.1", optional = true }
# Wallet dependencies
universal_wallet = { version = "0.5", optional = true }
rkv = { version = "0.17", optional = true }
bincode = { version = "1.3.1", optional = true }

# oobis dependecies
url = { version = "2.2.2", features = ["serde"], optional = true }
strum_macros = { version = "0.24", optional = true }
strum = { version = "0.24", optional = true }
reqwest = { version = "0.11", features = ["json", "rustls-tls", "blocking"], default-features = false, optional = true }

[dev-dependencies]
sodiumoxide = "0.2.6"
hex = "0.4.3"
tempfile = { version = "3.1" }
