on:
  workflow_call:
    inputs:
      component-name:
        required: true
        type: string
    outputs:
      img-tag:
        description: "Docker img tag"
        value: ${{ jobs.build.outputs.img-tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    outputs:
      img-tag: ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
    steps:
      - uses: actions/checkout@v3

      - name: Get tag
        id: repository
        run: echo "tag=$(git describe --tags HEAD)" > $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/keriox-${{inputs.component-name}}
          flavor: latest=true
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: witness.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
