name: Build docker images

on:
  push:
    tags:
      - witness-v\d+\.\d+\.\d+.*
      - watcher-v\d+\.\d+\.\d+.*

jobs:
  build-witness:
    uses: ./.github/workflows/build.yml
    with:
      component-name: witness

  build-release-witness:
    runs-on: ubuntu-latest
    needs: build-witness
    outputs:
      img-tag: ${{ needs.build-witness.outputs.img-tag }}
    steps:
      - run: "echo ${{ needs.build-witness.outputs.img-tag }}"

  build-watcher:
    uses: ./.github/workflows/build.yml
    with:
      component-name: watcher

  build-release-watcher:
    runs-on: ubuntu-latest
    needs: build-watcher
    outputs:
      img-tag: ${{ needs.build-watcher.outputs.img-tag }}
    steps:
      - run: "echo ${{ needs.build-watcher.outputs.img-tag }}"

  release:
    needs:
      - build-release-witness
      - build-release-watcher
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          body: |
            ### Images

            - Witness: [ ${{ needs.build-release-witness.outputs.img-tag }} ](https://${{needs.build-release-witness.outputs.img-tag}})
            - Watcher: [ ${{ needs.build-release-watcher.outputs.img-tag }} ](https://${{needs.build-release-watcher.outputs.img-tag}})
          removeArtifacts: true
          artifacts: ""
